unit TestQuestionsInterview;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, QuestionsInterview, System.SysUtils;

type
  // Test methods for class TSampleInterview

  TestTSampleInterview = class(TTestCase)

  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestIsOdd;
    procedure TestNotOdd;
    procedure TestPowerTwo;
  end;

implementation

procedure TestTSampleInterview.SetUp;
begin

end;

procedure TestTSampleInterview.TearDown;
begin

end;

procedure TestTSampleInterview.TestIsOdd;
begin
    CheckTrue( TSampleInterview.IsOdd( 5 ));
end;

procedure TestTSampleInterview.TestNotOdd;
begin
  CheckFalse( TSampleInterview.IsOdd( 2 ) );
end;

procedure TestTSampleInterview.TestPowerTwo;
begin
  CheckTrue( TSampleInterview.IsPowerTwo( 3 ));
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTSampleInterview.Suite);
end.

